---
- hosts: all
  tasks:
    - name: Install required dependencies
      yum:
        update_cache: true
        name: "{{ item }}"
      with_items:
      - git
      - nano
      - net-tools
      - bind-utils
      - firewalld
      - bridge-utils
      - bash-completion
      - kexec-tools
      - sos
      - psacct
      - openssl-devel
      - httpd-tools
      - NetworkManager
      - python-cryptography
      - python-devel
      - python-passlib
      - java-1.8.0-openjdk-headless
      - "@Development Tools"

    - name: Start Network service
      systemd:
        state: started
        name: NetworkManager

    - name: Enable Network service
      systemd:
        enabled: yes
        name: NetworkManager

    - name: Start FirewallD service
      systemd:
        state: started
        name: firewalld

    - name: Enable FirewallD service
      systemd:
        enabled: yes
        name: firewalld

    - name: Update /etc/hosts
      blockinfile:
        block: "{{ lookup('template', 'hostsfile.j2') }}"
        path: /etc/hosts
